---

- hosts: raspberry_cluster
  gather_facts: yes
  become: yes
  roles:
    - role: prereq
    - role: download
    - role: raspberrypi

- hosts: controller
  become: yes
  roles:
    - role: k3s/controller

- hosts: node
  become: yes
  roles:
    - role: k3s/node
