apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: cheap
  namespace: metallb-system
spec:
  addresses:
  - 10.0.0.200-10.0.0.215
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: cheap-add
  namespace: metallb-system
spec:
  ipAddressPools:
  - cheap
