---
k3s_version: v1.25.2+k3s1
ansible_user: debian
systemd_dir: /etc/systemd/system
controller_ip: "{{ hostvars[groups['controller'][0]]['ansible_host'] | default(groups['controller'][0]) }}"
extra_server_args: "--disable servicelb --disable-cloud-controller"
extra_agent_args: ""