---
all:
  children:
    raspberry_cluster:
      children:
        controller:
          hosts:
            controller1:
              ansible_host: 10.0.0.185
              ansible_user: cluster
              ansible_password: "{{ cluster_password }}"
        node:
          hosts:
            node1:
              ansible_host: 10.0.0.245
              ansible_user: cluster
              #ansible_ssh_private_key_file: /path/file
              ansible_password: "{{ cluster_password }}"
